version: '3.8'

services:
  auth_service:
    build:
      context: ./auth
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1

  main_app:
    build:
      context: ./main_app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1